name: Build and Publish Electron App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Electron App
        run: |
          npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install build tools
        run: |
          brew install libtool automake autoconf cmake pkg-config

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps --build-from-source

      - name: Build macOS installer
        run: npm run dist -- --mac

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: dist/*.dmg

  release:
    runs-on: windows-latest
    needs: [build-windows, build-macos]
    if: success()

    steps:
      - name: Publish Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npx electron-builder --publish always
